src/pages/events/2020/03/manchester-sitecore-usergroup.md
src/pages/events/2020/04/london-sitecore-usergroup.md

Updated date for Manchester UG + added speaker for April.

Content update

---

src/pages/events/2020/02/london-avanade-sitecore-usergroup.md
src/pages/events/2020/04/london-sitecore-usergroup.md

Updated venue details, added speaker for April UG
Changed speakers for February UG

Updated content

---

src/components/EventsList/eventsList.js
src/pages/events/2020/03/sugcon.md

Added sugcon.md for content
Changed output for eventslist if externalLink is used (title + read more button)
Relates to https://github.com/steviemcg/scuguk/issues/6

Added SUGCON block to Events listing

---

src/pages/events/2020/02/london-avanade-sitecore-usergroup.md

Updated Jeremy Davis's talk details

Updated speaking slot

---

src/pages/events/2020/02/london-avanade-sitecore-usergroup.md

Added details for Richard's talk

Updated content for feb usergroup

---

src/pages/events/2021/08/manchester-dept-sitecore-usergroup.md

(cherry picked from commit 056eef4e3469dacba198ffad40581fc04d61db6e)

add description for manchester sug talk

---

src/pages/events/2021/08/manchester-dept-sitecore-usergroup.md

some updates to add new talks to Manchester SUG

updates to manchester SUG

---

src/pages/events/2021/12/london-unrvld-december-sitecore-usergroup.md

new events page for London SUG in December

add december london usergroup events page

---

src/pages/events/2022/05/manchester-code-sitecore-usergroup.md

Merge May Manchester SUG Event Page

Add May Manchester SUG event page at Code

---

src/pages/events/2022/06/london-assurex-sitecore-usergroup.md

Due to change in the June'2022 event date, date changed to 29th June'2022

SUGUK-JUNE-2022-EventDeails

---

.github/workflows/main.yml

Sets up a Github workflow action to rebuild the site every 15 minutes (as a test!)

Test of regular builds

---

src/pages/events/2022/09/london-assurex-sitecore-usergroup.md

Removed the Event details for AUG Month and Added the SEPT month details.

Changes for SUG London Events

---

src/pages/events/2022/11/manchester-dept-sitecore-usergroup.md

updates to all talks to add more info

---

src/components/EventsList/event.scss
src/pages/events/2023/02/london-avanade-sitecore-usergroup.md
src/templates/event-page.js

Prettyfied the events page and tweaked the details of the London events.

Styling updates and London event updates

---

src/pages/events/2023/02/london-avanade-sitecore-usergroup.md

Adds details + times for the London 2023 Feb event.

Updates for London Feb event

---

src/pages/events/2023/04/newcastle-epam-sitecore-usergroup.md

Feat: newcastle april 2023

---

src/pages/events/2023/09/manchester-code-sitecore-usergroup.md

feat: initial add of Manchester Code SUG September 2023

---

netlify.toml

Fixes existing links to Manchester site for new URL structure

Adds redirect for old event URL format

---

src/data/events/2023-09-manchester-code-sitecore-usergroup.yml

add sug youtube video links for all 3 talks

feat: add man sug youtube video links

---

src/pages/events/[key].tsx

Adding some more Twitter specific metadata in to see if this gets link previews properly working.

Added some twitter specific metadata for events

---

src/data/speakers/kateorlova.yml

For some reason, my boss had my name in the data...
Fixing that for MVP renewal season...

Update Speaker data in kateorlova.yml

---

src/data/events/2024-01-manchester-unrvld-sitecore-usergroup.yml

First pass at adding relevant info. (Don't have details from Matt yet)
Let me know if I've got any settings / schema wrong here and I can correct.

Adding known talk info for Manchester. Enable booking

---

src/components/Footer/Footer.tsx

Now always shows the current year at time of build

Fix the copyright year

---

src/data/events/2024-09-manchester-code-sitecore-usergroup.yml

feature: add-peters-talk-manchester-sep-sug-2024

---

src/data/events/2024-09-manchester-code-sitecore-usergroup.yml

feat: sug-man-sep-tweak-kates-talk
